### ISSUE TITLE
[canvasargs] bug

### ISSUE THREAD

**Issue by oliverstotz** [iem-projects/pd-iemguts#10]
Hi,

I noticed a bug in the [canvasargs] object, easy to reproduce in its help patch.

If i send a list of new arguments to [canvasargs], only the "raw" message reflects the change. "bang" still outputs the old arguments.

Steps to reproduce in "canvasargs-help.pd":
1.) click the message [list quite a lot of arguments(
2.) click message [bang( ---> old arguments at output
3.) click message [raw( ---> new arguments at ouput

**Comment by oliverstotz** [comment]
Addendum: This bug was introduced in iemguts v 0.3

**Comment by umlaeute** [comment]
well, the help-patch also says:
> NOTE: When changing the arguments (via a "list" message), the dollar-expanded variables (obtained via 'bang' will wrongly reflect the original arguments. The raw arguments will always be correct.


iirc, iemguts-0.3 introduced the `raw` message, and changed the `bang` message to the expanded (but not re-evaluated) flavor.
