### ISSUE TITLE
[canvasposition 0] crashes PD when in main window

### ISSUE THREAD

**Issue by oliverstotz** [iem-projects/pd-iemguts#11]
Hi,

Version 0.4 introduced a new info coming out of [canvasposition]'s rightmost outlet, "size x y" which is very useful ! Appreciated !

Unfortunately, since 0.4, banging a [canvasposition] whose parent hierarchy point's to itself crashes PD.

Example is attached.

Best

Oliver
[canvasposition_crash_example_240424.zip](https://github.com/iem-projects/pd-iemguts/files/15096442/canvasposition_crash_example_240424.zip)

**Comment by umlaeute** [comment]
i'm pretty sure i've fixed this a few weeks ago.

but haven't found it yet...

**Comment by umlaeute** [comment]
found it

**Comment by umlaeute** [comment]
the story behind the fix: on the train to szbg where i had been invited to perform a piece that i have been performing for more than 10 years (but not recently), all of a sudden Pd started to crash consistently.

slightly nervous, i did a quick fix between radstadt and bihofen. :relieved:
