### ISSUE TITLE
Why canvasposition first outlet gives coordinates  divided by two when zoom = 2

### ISSUE THREAD

**Issue by jyg** [iem-projects/pd-iemguts#12]
Hi, I cannot understand why, when the object is banged, the first outlet delivers the coordinates values divided by 2, when zoom = 2.  In the source code it's located here :
https://github.com/iem-projects/pd-iemguts/blob/999a9a5209af7a8abd80264f06ac7e84a751a8ad/src/canvasposition.c#L91C1-L92C30

In a previous issue https://github.com/iem-projects/pd-iemguts/issues/8 they were multiplied by two. It was considered a bug.
but now I don't know what to think.

Fortunately, this can be fixed in the patch using the zoom message on third outlet.

**Comment by umlaeute** [comment]
indeed.
i stumbled upon this myself a while ago, but had no time to investigate.

i'm pretty sure it is (still) a bug.

**Comment by umlaeute** [comment]
the other question is what to do about the "object-size" (coming out of the 3rd outlet with the `size` selector).
it currently is also scaled (up) by the zoom-factor, and has always been like this.

**Comment by umlaeute** [comment]
ah i just found out: older versions of Pd (namely e.g. 0.48) did require the scaling for proper values.
so iemguts just needs to adjust for newer Pd.

the incompatible change in Pd was https://github.com/pure-data/pure-data/commit/a6e3bbab4023d9c625b1eea95341027e43c45547 (leading to the 0.50-0 release)

**Comment by jyg** [comment]
Thanks !
