### ISSUE TITLE
[oreceive] overwrites [r]

### ISSUE THREAD

**Issue by LGoodacre** [iem-projects/pd-iemguts#4]
If you create the object [iemguts/oreceive], then every time you create the object [r] thereafter, it will be [oreceive] and not [receive]. [oreceive] can do everything that [receive] can so this bug doesn't damage anything, but it's still a little annoying.

**Comment by umlaeute** [comment]
could you please come up with a use-case that exhibits the *annoyingness* of the current behaviour?

**Comment by LGoodacre** [comment]
Certainly.
A user loads an abstraction which contains [iemguts/oreceive], and unwittingly overwrites the [r] designation. Then they create an [r] object, find that it has an inlet, and use it. Next time they load PD, the get a "connection failed" error message and wonder why their patch is broken.
