### ISSUE TITLE
initbang and subpatches

### ISSUE THREAD

**Issue by porres** [iem-projects/pd-iemguts#5]
Hi, the help file of initbang says it won;t trigger bangs in subpatches. But I tested it and it actually triggers a bang in subpatches.

**Comment by porres** [comment]
also, seems to me that bangs are sent in subpatches before initbangs in parent patches.

**Comment by umlaeute** [comment]
what's wrong with triggering subpatches before parent patches?

**Comment by porres** [comment]
> what's wrong with triggering subpatches before parent patches?

nothing, I misspoke, didn't mean it was supposed to be wrong, it's just an extra information I found about it, sorry

**Comment by umlaeute** [comment]
ah i see. thanks for the clarification.

**Comment by umlaeute** [comment]
i've updated the docs to be a bit more specific about the "not working in subpatches" part (while initbang sends out a bang, it does so too late to be useful)
