### ISSUE TITLE
canvasposition behavior while zooming window (ctrl + '+') 

### ISSUE THREAD

**Issue by jyg** [iem-projects/pd-iemguts#8]
Hi,
With the new zooming feature of pd windows,  `[canvasposition]`'s behavior isn't yet consistent with cnv's behavior.
The coordinates of cnv objects remain unchanged with zoom = x2, but the coordinates given by `[canvasposition]` are multiplied by 2.
Reciprocally, to change coords of objects, you have to multiply them by 2 with `[canvasposition]` object.

Is this a choice or a bug ?
Thanks.
(pd 0.48-1  linux)

[test-canvasposition.pd.zip](https://github.com/iem-projects/pd-iemguts/files/2067542/test-canvasposition.pd.zip)

P.S.  seems that there is the same question with coords given by `[receivecanvas]` messages.

**Comment by umlaeute** [comment]
for `[canvasposition]`, i'm pretty sure it's a bug.

for `[receivecanvas]`, I'm tending towards not-a-bug, as this object gives you the raw communication from the canvas, which happens to contain the coordinates as they are (pre-multiplied).

**Comment by jyg** [comment]
Hi,
The problem  I have with` [receivecanvas]` is how to know inside a GOP-subpatch if zooming is x1 or x2 ?
With` [receivecanvas]` in main patch, you can receive messages like "zoom 1" or "zoom 2" if you do zooming on this patch.
But if this patch contains a gop-subpatch or a gop-abstraction, `receivecanvas` inside this subpatch doesn't catch zoom messages, and the subpatch cannot  know if it will be drawn with scale factor x1 or x2. (unless you know the hierarchy level). Now, as a workaround, I can send a global ZOOM message from the main patch.

**Comment by umlaeute** [comment]
i understand the issue with `[receivecanvas]`, but i don't have any solution for it yet.

**Comment by umlaeute** [comment]
arguably, the entire zoom-implementation in Pd is buggy. the core shouldn't know anything about whether the GUI displays things as zoomed or not.
