### ISSUE TITLE
canvasindex-help.pd doc : about optional argument for parent depth

### ISSUE THREAD

**Issue by jyg** [iem-projects/pd-iemguts#9]
Hi,
I have trouble with the second example mentionned in the helpfile for canvasindex : [pd objectcount].
I cannot get the total number of objects of the patch unless  I change,  in the subpatch objectcount, [canvasindex 1] with [canvasindex].
I'm a little confused with the depth specified by optional argument of canvasindex. 
I think that 0 refers to parent canvas, 1 to grand-parent ( unlike for sendcanvas or receivecanvas, where 1 refers to parent and 2 to grand parent patch).
Or I am wrong ?
Thanks

**Comment by umlaeute** [comment]
you are right about the inconsistent parent-depth numbering.

the help-patch has been updated with 9cefc152941f6d61f298c6886b1f3026672c20b8
